apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: default
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: docker.io/bitnami/wordpress:6.3.0 # {"$imagepolicy": "flux-system:wordpress"}
          imagePullPolicy: Always
          # ports:
          #   - name: http
          #     containerPort: 9898
          #     protocol: TCP
