---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: wordpress
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: wordpress
  policy:
    semver:
      range: 6.3.x
